### ISSUE TITLE
Motivation for packing the companion package in a text file?

### ISSUE THREAD

**Issue by mikkmart** [RConsortium/submissions-pilot1-to-fda#5]
First of all, thanks for sharing this important (and impressive) work! Something I was left wondering: What was the motivation for packing the companion R package as [a text file](https://github.com/RConsortium/submissions-pilot1-to-fda/blob/74802a7dda4fb47b415aaed92b93cf6b05aedd31/m5/datasets/rconsortiumpilot1/analysis/adam/programs/r0pkg.txt) for the submission, rather than just including the source package directly?

**Comment by elong0527** [comment]
It is due to the restriction of eCTD package requirement. 

- all filename shall be lower cases. (different from R file convention e.g. `.R`, `.Rmd`)
- "Sponsors should submit software programs in ASCII text format; however, executable file extensions should not be used"
(`.zip`, `.tar` is not allowed)

A text file is just one way to address those issues as described in. 

https://r4csr.org/submission-overview.html

**Comment by mikkmart** [comment]
Thanks for clarifying that! I was thinking about including the package source directly (not bundled to zip/tar), but then I guess there would be an issue with at least `DESCRIPTION` and `NAMESPACE` not having a file extension to adhere to the whitelisted ones.

And yeah, I can now see that even requirements like all lower case names would then require some post-processing for a package before submission. And at that point -- if you have to start modifying the package source at all -- it makes a lot of sense to have a tool like pkglite to just handle all that instead.
